mutation cartAttributesUpdate(
  $attributes: [AttributeInput!]!
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartAttributesUpdate(attributes: $attributes, cartId: $cartId) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartBuyerIdentityUpdate(
  $buyerIdentity: CartBuyerIdentityInput!
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartBuyerIdentityUpdate(buyerIdentity: $buyerIdentity, cartId: $cartId) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartCreate(
  $cartInput: CartInput
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartCreate(input: $cartInput) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartDeliveryAddressesAdd(
  $addresses: [CartSelectableAddressInput!]!
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartDeliveryAddressesAdd(addresses: $addresses, cartId: $cartId) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartDeliveryAddressesRemove(
  $addressIds: [ID!]!
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartDeliveryAddressesRemove(addressIds: $addressIds, cartId: $cartId) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartDeliveryAddressesUpdate(
  $addresses: [CartSelectableAddressUpdateInput!]!
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartDeliveryAddressesUpdate(addresses: $addresses, cartId: $cartId) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartDiscountCodesUpdate(
  $cartId: ID!
  $discountCodes: [String!]!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartDiscountCodesUpdate(cartId: $cartId, discountCodes: $discountCodes) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}
mutation cartGiftCardCodesRemove(
  $appliedGiftCardIds: [ID!]!
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartGiftCardCodesRemove(cartId: $cartId, appliedGiftCardIds: $appliedGiftCardIds) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartGiftCardCodesUpdate(
  $cartId: ID!
  $giftCardCodes: [String!]!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartGiftCardCodesUpdate(cartId: $cartId, giftCardCodes: $giftCardCodes) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartLinesAdd(
  $cartId: ID!
  $lines: [CartLineInput!]!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartLinesAdd(cartId: $cartId, lines: $lines) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartLinesRemove(
  $cartId: ID!
  $lineIds: [ID!]!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartLinesRemove(cartId: $cartId, lineIds: $lineIds) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartLinesUpdate(
  $cartId: ID!
  $lines: [CartLineUpdateInput!]!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartLinesUpdate(cartId: $cartId, lines: $lines) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartNoteUpdate(
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $note: String!
  $language: LanguageCode
) @inContext(language: $language) {
  cartNoteUpdate(cartId: $cartId, note: $note) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

mutation cartSelectedDeliveryOptionsUpdate(
  $cartId: ID!
  $selectedDeliveryOptions: [CartSelectedDeliveryOptionInput!]!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cartSelectedDeliveryOptionsUpdate(
    cartId: $cartId
    selectedDeliveryOptions: $selectedDeliveryOptions
  ) {
    cart {
      ...CartFields
    }
    userErrors {
      ...CartUserErrors
    }
    warnings {
      message
    }
  }
}

query getCart(
  $cartId: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $language: LanguageCode
) @inContext(language: $language) {
  cart(id: $cartId) {
    ...CartFields
  }
}

query checkoutURL($cartId: ID!, $language: LanguageCode) @inContext(language: $language) {
  cart(id: $cartId) {
    checkoutUrl
  }
}
