import shopifyStorefrontCall from '..';
import {
  cleanCollections,
  cleanImage,
  cleanProducts,
  cleanVariants,
} from '../helpers';
import productQueries from './productQueries';

/**
 * It takes a product ID and returns a list of recommended products.
 * @param productId - The ID of the product you want to get recommendations for.
 * @returns An array of products.
 */
export const getProductRecommendation = async (productId) => {
  try {
    const res = await shopifyStorefrontCall(
      productQueries.queryProductRecommendations,
      {
        productId,
      }
    );
    const product = res?.data?.productRecommendations;
    if (product) return cleanProducts(product);
    return null;
  } catch (error) {
    return console.error(error);
  }
};

/**
 * It takes a product handle as an argument, makes a call to the Shopify Storefront API, and returns
 * the product data.
 * @param handle - the product handle
 * @returns The product object with the images and variants arrays.
 */
export const getProduct = async (handle) => {
  try {
    const res = await shopifyStorefrontCall(productQueries.queryProduct, {
      handle,
    });
    const product = res?.data?.product;
    if (product) {
      return {
        ...product,
        images: cleanImage(product?.images?.edges),
        variants: cleanVariants(product?.variants?.edges),
      };
    }
    return null;
  } catch (error) {
    return console.error(error);
  }
};

/**
 * It's a function that takes in a sortKey and a first argument, and returns a promise that resolves to
 * an object with a products key, which is an array of products
 * @param sortKey - The key to sort the products by.
 * @param first - The number of products to return.
 * @returns An array of products.
 */
export const getProducts = async (sortKey, first) => {
  try {
    const res = await shopifyStorefrontCall(productQueries.queryProducts, {
      first,
      sortKey,
    });
    const products = res?.data?.products.edges;
    if (products) return { products: cleanProducts(products) };
    return null;
  } catch (error) {
    return console.error(error);
  }
};

/**
 * It takes a query, a delegate token, and an IP address, and returns a list of products that match the
 * query
 * @param query - the search query
 * @param delegateToken - The token that is generated by the Shopify API
 * @param ip - '127.0.0.1'
 * @returns An array of products.
 */
export const searchProducts = async (query, delegateToken, ip) => {
  try {
    const res = await shopifyStorefrontCall(
      productQueries.searchProducts,
      {
        query: `title:${query}`,
      },
      delegateToken,
      ip
    );

    const response = res?.data?.products?.edges;

    if (response) {
      const products = response.map((product) => ({
        ...product.node,
        images: cleanImage(product.node?.images?.edges),
        collections: cleanCollections(product.node?.collections?.edges),
      }));
      return products;
    }
    return null;
  } catch (error) {
    return console.error(error);
  }
};
