name: Codacy Analysis CLI

on:
  push:
    branches:
      - main
      - develop

jobs:
  codacy-analysis-cli:
    name: Run Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
