name: Codacy Analysis CLI

on:
  push:
    branches:
      - main
      - develop

jobs:
  codacy-analysis-cli:
    name: Run Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v1
