# Wait to run until after the Vercel deployment has finished
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment_status
name: Wait for Vercel deployment

on: deployment_status

jobs:
  pa11y:
    name: Run pa11y-ci
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run pa11y-ci
        run: npm run pa11y-ci -- --sitemap ${{ github.event.deployment_status.target_url }}/sitemap.xml
